#test_it_accepts_data (?)

# test_it_has_a_name_key_value_pair

# test_it_accepts_name_and_dataset_when_initialized

# test_kg_part_by_year_returns_list_of_years_and_rates

# test_kg_part_by_year_returns_truncated_3_digit_floating_point_number

# test_kg_part_in_year_accepts_one_arg

# test_kg_part_in_year_returns_rate_for_given_year
